sudo: false
language: scala
scala: 2.12.6

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
# 8
    - jdk: oraclejdk8
    - jdk: openjdk8
# 10
    - jdk: oraclejdk10
    - install: . ./install-jdk.sh -F 10 -L GPL
# 11
    - install: . ./install-jdk.sh -F 11 -L BCL
    - install: . ./install-jdk.sh -F 11 -L GPL

script: sbt test
